*       COMMON6.
*       -------
*
      IMPLICIT REAL*8  (A-H,O-Z)
*
      PARAMETER  (NMAX=10100,XEPS=1.D-03)
      PARAMETER  (ID=3,NTAB=32)
*
      SAVE
*
      COMMON/NBODY/BODY(NMAX),X(ID,NMAX),XDOT(ID,NMAX),XMRPL(NMAX),
     *  RHOPL(NMAX),XFUNC(NMAX),
     *  XMR1(NMAX),XMR2(NMAX),ZMASS,XMINT,XM1,XM2,XM1TOT,XM2TOT,
     *  IND(NMAX),JLIST(NMAX),N
*
      COMMON/WORK2/RHO(NMAX),RHOC(NMAX),PHIDBL(NMAX)
      COMMON/RANDO/IDUM,IY,IDUM2,IV(NTAB)
*
