diff $1/bindat.f $2/ >> OUT 
diff $1/binout.f $2/ >> OUT
diff $1/binev.f $2/ >> OUT
diff $1/brake.f $2/ >> OUT 
diff $1/brake2.f $2/ >> OUT 
diff $1/brake3.f $2/ >> OUT 
diff $1/bsetid.f $2/ >> OUT 
diff $1/chaos2.f $2/ >> OUT
diff $1/chaos0.f $2/ >> OUT 
diff $1/chaos.f $2/ >> OUT 
diff $1/cmbody.f $2/ >> OUT 
diff $1/coal.f $2/ >> OUT 
diff $1/comenv.f $2/ >> OUT 
diff $1/corerd.f $2/ >> OUT 
diff $1/chrect.f $2/ >> OUT 
diff $1/cmbody.f $2/ >> OUT 
diff $1/degen.f $2/ >> OUT
diff $1/dgcore.f $2/ >> OUT 
diff $1/eccmod.f $2/ >> OUT 
diff $1/ecirc.f $2/ >> OUT 
diff $1/efac2.f $2/ >> OUT 
diff $1/efac3.f $2/ >> OUT
diff $1/expel.f $2/ >> OUT 
diff $1/expel2.f $2/ >> OUT
diff $1/events.f $2/ >> OUT
diff $1/giant.f $2/ >> OUT 
diff $1/giant2.f $2/ >> OUT
diff $1/giant3.f $2/ >> OUT 
diff $1/gntage.f $2/ >> OUT 
diff $1/grrad.f $2/ >> OUT 
diff $1/hcorr.f $2/ >> OUT
diff $1/hiarch.f $2/ >> OUT 
diff $1/hicirc.f $2/ >> OUT 
diff $1/hidat.f $2/ >> OUT 
diff $1/higrow.f $2/ >> OUT 
diff $1/himax.f $2/ >> OUT 
diff $1/himod.f $2/ >> OUT
diff $1/hipop.F $2/hipop.f >> OUT 
diff $1/hirect.f $2/ >> OUT 
diff $1/histab.f $2/ >> OUT 
diff $1/hmdot.f $2/ >> OUT 
diff $1/hmdot2.f $2/ >> OUT
diff $1/hrdiag.f $2/ >> OUT 
diff $1/hrplot.F $2/hrplot.f >> OUT 
diff $1/hut.f $2/ >> OUT 
diff $1/hut2.f $2/ >> OUT
diff $1/kick.F $2/kick.f >> OUT 
diff $1/kick2.f $2/ >> OUT
diff $1/magbrk.f $2/ >> OUT 
diff $1/mdot.F $2/mdot.f >> OUT
diff $1/merge.f $2/ >> OUT 
diff $1/merge2.f $2/ >> OUT 
diff $1/mix.f $2/ >> OUT 
diff $1/mloss.f $2/ >> OUT 
diff $1/mlwind.f $2/ >> OUT 
diff $1/mrenv.f $2/ >> OUT
diff $1/newtev.f $2/ >> OUT 
diff $1/nstab.f $2/ >> OUT 
diff $1/proto_star.f $2/ >> OUT 
diff $1/qtides.f $2/ >> OUT 
diff $1/rl.f $2/ >> OUT 
diff $1/roche.f $2/ >> OUT 
diff $1/rpmax.f $2/ >> OUT 
diff $1/rpmax2.f $2/ >> OUT 
diff $1/rpmin.f $2/ >> OUT
diff $1/spiral.f $2/ >> OUT 
diff $1/stability.f $2/ >> OUT 
diff $1/star.f $2/ >> OUT 
diff $1/synch.f $2/ >> OUT
diff $1/tcirc.f $2/ >> OUT
diff $1/tides.f $2/ >> OUT
diff $1/tides2.f $2/ >> OUT 
diff $1/tides3.f $2/ >> OUT 
diff $1/touch.f $2/ >> OUT 
diff $1/tpert.f $2/ >> OUT 
diff $1/trdot.f $2/ >> OUT 
diff $1/trdot2.f $2/ >> OUT 
diff $1/trflow.f $2/ >> OUT 
diff $1/tstab.f $2/ >> OUT
diff $1/zcnsts.f $2/ >> OUT
diff $1/zfuncs.f $2/ >> OUT 
